### ISSUE TITLE
subscripts rendered onto separate lines

### ISSUE THREAD

**Issue by slesniak** [glutanimate/cloze-overlapper#20] opened 2019-02-11 19:54 UTC
## Prerequisite checklist

* [ x] In case of a bug: Have you tried restarting Anki?
* [ n/a] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [ looked through issues] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [ x] Did you perform a cursory search through the existing issue reports?

When writing a list of items with cloze overlapper

[Be as specific as possible. Provide screenshots if you think they can help.]

## How can we reproduce the problem?

[What were you doing when the problem occurred?]

I generated an overlapping cloze with chemical formulas which contained subscripts

**Expected behavior:** subscripts should be rendered

**Actual behavior:** subscripts are on their own lines

template:<img width="497" alt="screen shot 2019-02-11 at 11 36 54 am" src="https://user-images.githubusercontent.com/1088320/52589249-3ae68700-2df3-11e9-9877-a4211ca2f3b4.png">
as rendered:<img width="126" alt="screen shot 2019-02-11 at 11 37 07 am" src="https://user-images.githubusercontent.com/1088320/52589250-3ae68700-2df3-11e9-92a9-19b329632096.png">
 
simplified test case:
template:
<img width="121" alt="screen shot 2019-02-11 at 11 52 04 am" src="https://user-images.githubusercontent.com/1088320/52589373-839e4000-2df3-11e9-9639-a726b5279a52.png">
as rendered:
<img width="501" alt="screen shot 2019-02-11 at 11 52 13 am" src="https://user-images.githubusercontent.com/1088320/52589375-839e4000-2df3-11e9-87a8-3cbfb96e612b.png">

**Reproducible?:** 
yes

## Version information

**Anki**

Version 2.1.8 (71e0c880)
Qt 5.12.0 PyQt 5.11.3
cloze-overlapper-release-v0.4.0-alpha.0-anki21.zip (Patreon alpha release)

**System**

- Operating system: OS X
- Version: 10.14.2

**Comment by glutanimate** [comment] 2019-02-15 20:07
Hey Shawn,

Thanks for the exemplary bug report!

Sadly support for subscripts and other HTML tags has been rather limited from the beginning. Although this isn't a definitive solution, one thing you could do for the time being is to manually cloze each line yourself (using Ctrl+Shift+C). This should work regardless of the HTML formatting present.

The proper solution of course would be for the add-on to more intelligently tell line-breaks apart from other types of HTML tags. However, because the question what does and doesn't constitute a line-break can be quite complex in HTML, this is not a trivial problem to solve.

Still, I'll make sure to give this another look before the v0.4.0 release!

Please feel free to track the progress of this in #5 (the issue described is not the exact same, but since both stem from the same root cause I will be closing this in favor of the older bug report).

**Closed by glutanimate** 2019-02-15 20:07 UTC
